# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(759, 591)
        self.coords = QtWidgets.QLineEdit(Form)
        self.coords.setGeometry(QtCore.QRect(10, 550, 231, 20))
        self.coords.setObjectName("coords")
        self.delta = QtWidgets.QLineEdit(Form)
        self.delta.setGeometry(QtCore.QRect(260, 550, 321, 20))
        self.delta.setObjectName("delta")
        self.ready = QtWidgets.QPushButton(Form)
        self.ready.setGeometry(QtCore.QRect(600, 550, 141, 23))
        self.ready.setObjectName("ready")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 721, 521))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.coords.setText(_translate("Form", "Введите координаты:"))
        self.delta.setText(_translate("Form", "Введите маштаб от 0 до 0.0000001:"))
        self.ready.setText(_translate("Form", "Показать"))
